Bookstore CMS: Use Redux in React component
Profsain/Bookstore-CMS pull request #3
Opened 2022-07-19 14:57 UTC by Profsain

- Update the books state
- connect redux to react component
- Added addbook redux functionality
- Added remove button dispatch
- Added check status dispatch
-
![screencapture-localhost-3000-2022-07-19-15_55_05](https://user-images.githubusercontent.com/32632836/179782096-edbbad19-2f3c-4c65-bf33-4cab6ff7a4e6.png)

2022-07-19 16:40 UTC, topeogunleye requested changes
> # Changes Required 
> ### Hi @Profsain,
> Nice job, you are almost there.
> 
> ![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## (Highlights) Good Points: 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:
> * PR has a good summary description :heavy_check_mark:
>
> ## (Changes Required) Aspects to improve: 
> * [ ]  Please check my inline comments.
> 
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> **Cheers and Happy coding! :clap::clap::clap:**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear
> Please, remember to tag @topeogunleye in your question so I can receive the notification.
>
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-19 16:40 UTC, topeogunleye commented on src/components/Bookcard.js
> +    dispatch(removeBook());
- [ ] Your removeBook function in  `../redux/books/books` is expecting an id as a parameter, but you didn't add it here.  Please kindly add your id parameter to ensure your remove book functionality is working.

2022-07-19 16:40 UTC, topeogunleye commented on src/components/Bookcard.js
> +            onClick={removeBookHandler}
- [ ] Kindly ensure that your removeBookHandler function takes the id from the book data and dispatches the `removeBook` action creator with the id as its argument

2022-07-19 16:40 UTC, topeogunleye commented on src/components/Categories.js
> +      </button>
- [ ] I kindly suggest that you display the return statement of 'Under Construction' underneath your button. Here is an example video below:

https://user-images.githubusercontent.com/52934128/179803825-4673312f-0373-48c6-bc54-2dc15787d224.mp4

2022-07-20 11:19 UTC, Rustamxon7 approved these changes
## Hello @Profsain👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-07-20 11:48 UTC, merged